"""empty message

Revision ID: 49b1a2d8b5f3
Revises: bb3d8d96c0e1
Create Date: 2023-04-22 16:43:38.182127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b1a2d8b5f3'
down_revision = 'bb3d8d96c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
