"""empty message

Revision ID: b6cb14312465
Revises: ddd2ea203eca
Create Date: 2023-05-03 15:48:21.273792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6cb14312465'
down_revision = 'ddd2ea203eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('age_rate')
    op.drop_table('_alembic_tmp_anime')
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ageRate', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_anime_ageRate_rate_age'), 'rate_age', ['ageRate'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_anime_ageRate_rate_age'), type_='foreignkey')
        batch_op.drop_column('ageRate')

    op.create_table('_alembic_tmp_anime',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('altName', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('seriesCount', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('reliese_type', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('_genre', sa.VARCHAR(), nullable=True),
    sa.Column('fullDescription', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('ageRate', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ageRate'], ['age_rate.id'], ),
    sa.ForeignKeyConstraint(['reliese_type'], ['type.id'], ),
    sa.ForeignKeyConstraint(['status'], ['anime_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('age_rate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rate', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_age_rate')
    )
    # ### end Alembic commands ###
