"""empty message

Revision ID: ddd2ea203eca
Revises: bd51c4b58380
Create Date: 2023-04-22 18:11:58.645704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd2ea203eca'
down_revision = 'bd51c4b58380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_review_user_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_author_user'), 'user', ['author'], ['id'])
        batch_op.drop_column('user')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_review_author_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_review_user_user', 'user', ['user'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
